name: CI/CD

on:
  push:
    branches:
      - 'searce_yash_gh_actions_test'

env:
  STAGING_CLUSTER: "ismfg-scratch"

jobs:
  install-apache-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GH_GCP_SA_SECRET }}'

      - name: Install Gcloud CLI, Helm, Kubectl
        run: | 
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          #sudo apt-get update && sudo apt-get install google-cloud-cli


          #curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-474.0.0-linux-x86_64.tar.gz
          #tar -xf google-cloud-cli-474.0.0-linux-x86_64.tar.gz
          #./google-cloud-sdk/install.sh --quiet

          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          #curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          #chmod 700 get_helm.sh
          #./get_helm.sh

          sudo apt-get update && sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin


      - name: Set the Remote proxy to access GKE cluster
        run: |
          gcloud container clusters get-credentials ismfg-scratch --region europe-west2 --project ismfg-scratch

          export HTTPS_PROXY=35.246.41.60:8888
          export HTTP_PROXY=35.246.41.60:8888


      - name: Install test apache/httpd through helm
        run: |  
          kubectl create ns apache
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install apache bitnami/apache --set service.type=LoadBalancer -n apache
